[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && python manage.py collectstatic --noinput"

[deploy]
startCommand = "python manage.py migrate && gunicorn agendamento_salao.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/admin/login/"
healthcheckTimeout = 100

[service]
internalPort = 8000