[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python manage.py migrate && gunicorn agendamento_salao.wsgi:application"
healthcheckPath = "/admin/login/"
healthcheckTimeout = 100

[service]
internalPort = 8000