services:
  - type: web
    name: cabelereiro-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn agendamento_salao.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: cache
          property: connectionString

  - type: worker
    name: celery-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A agendamento_salao worker --pool=gevent -l info

databases:
  - name: agendamento-db
    databaseName: agendamento
    plan: free 