# Generated by Django 5.0.1 on 2024-11-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estabelecimento',
            options={'verbose_name': 'Estabelecimento', 'verbose_name_plural': 'Estabelecimentos'},
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='status',
            field=models.CharField(choices=[('disconnected', 'Desconectado'), ('connected', 'Conectado'), ('pending_connection', 'Aguardando Conexão'), ('error', 'Erro')], default='disconnected', max_length=50),
        ),
    ]
