# Generated by Django 5.0.1 on 2024-12-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='bot_ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='dias_atendimento',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='horario_atendimento_fim',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='horario_atendimento_inicio',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='mensagem_boas_vindas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='mensagem_fora_horario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
