# Generated by Django 5.0.1 on 2024-11-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_estabelecimento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='telefone',
            field=models.CharField(default=5511999329999, max_length=20),
            preserve_default=False,
        ),
    ]
