# Generated by Django 5.0.1 on 2024-11-21 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_estabelecimento_is_active_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('default_duration', models.IntegerField(help_text='Duração padrão em minutos')),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='status',
            field=models.CharField(default='disconnected', max_length=50),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='endereco',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='horario_funcionamento',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='whatsapp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterModelTable(
            name='estabelecimento',
            table='estabelecimento',
        ),
        migrations.CreateModel(
            name='SalonService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('active', models.BooleanField(default=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estabelecimento')),
                ('system_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.systemservice')),
            ],
            options={
                'unique_together': {('system_service', 'estabelecimento')},
            },
        ),
    ]
