# Generated by Django 5.0.1 on 2024-11-25 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profissional',
            options={'verbose_name': 'Profissional', 'verbose_name_plural': 'Profissionais'},
        ),
    ]
