# Generated by Django 5.0.1 on 2024-11-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemservice_estabelecimento_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='horario_funcionamento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
