# Generated by Django 5.0.1 on 2025-01-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemconfig_lead_tags_systemconfig_mensagem_vendas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemconfig',
            options={},
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='bot_ativo',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='dias_atendimento',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='horario_atendimento_fim',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='horario_atendimento_inicio',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='lead_tags',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='mensagem_boas_vindas',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='mensagem_fora_horario',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='mensagem_vendas',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='vendas_ativas',
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='bot_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='status',
            field=models.CharField(default='disconnected', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='support_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
