# Generated by Django 5.0.1 on 2025-01-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_systemconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='last_qr_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='qr_code_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='status',
            field=models.CharField(choices=[('disconnected', 'Desconectado'), ('connected', 'Conectado'), ('pending', 'Pendente'), ('error', 'Erro')], default='disconnected', max_length=20),
        ),
    ]
