# Generated by Django 5.0.1 on 2024-11-26 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_custom_permissions_user_last_activity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_whatsapp', models.CharField(max_length=20)),
                ('evolution_instance_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('disconnected', 'Desconectado'), ('connected', 'Conectado'), ('pending_connection', 'Aguardando Conexão'), ('error', 'Erro')], default='disconnected', max_length=50)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cliente', models.CharField(max_length=20)),
                ('bot_ativo', models.BooleanField(default=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estabelecimento')),
            ],
            options={
                'unique_together': {('estabelecimento', 'numero_cliente')},
            },
        ),
    ]
