# Generated by Django 5.0.1 on 2025-01-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_create_interacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interacao',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='interacao',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='interacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='interacao',
            name='resposta',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='interacao',
            table='core_interacao',
        ),
    ]
