# Generated by Django 5.0.1 on 2024-11-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_systemconfig_botconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='dias_atendimento',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='horario_atendimento_fim',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='horario_atendimento_inicio',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='ignorar_grupos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='mensagem_bot_desativado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='mensagem_fora_horario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='tempo_debounce',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='interacao',
            name='cliente_satisfeito',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='interacao',
            name='intencao',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interacao',
            name='sucesso',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='interacao',
            name='tempo_resposta',
            field=models.FloatField(null=True),
        ),
    ]
