# Generated by Django 5.0.1 on 2025-01-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_interacao_options_interacao_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemconfig',
            options={'verbose_name': 'Configuração do Sistema', 'verbose_name_plural': 'Configurações do Sistema'},
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='bot_settings',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='evolution_instance_id',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='last_qr_code',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='qr_code_timestamp',
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='bot_ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='evolution_settings',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='horario_atendimento',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='prompt_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='webhook_settings',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='status',
            field=models.CharField(default='disconnected', max_length=20),
        ),
    ]
