# Generated by Django 5.0.1 on 2024-11-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_botconfig_dias_atendimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='aceitar_nao_clientes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='mensagem_nao_cliente',
            field=models.TextField(blank=True, default='Olá! Para melhor atendê-lo, por favor, faça seu cadastro em nosso salão.'),
        ),
    ]
