# Generated by Django 5.0.1 on 2025-01-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_systemconfig_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interacao',
            name='resolvido',
        ),
        migrations.AddField(
            model_name='interacao',
            name='is_lead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interacao',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('em_atendimento', 'Em Atendimento'), ('convertido', 'Convertido'), ('perdido', 'Perdido')], default='novo', max_length=20),
        ),
        migrations.AlterField(
            model_name='interacao',
            name='resposta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interacao',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
    ]
